name: Publish
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build
      run: |
        curl -LO \
          https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-1-amd64.deb
        sudo dpkg -i pandoc-*.deb
        sudo apt-get update -y
        sudo apt-get install -y fonts-noto-cjk texlive-xetex
        mkdir -p $HOME/.local/bin
        pushd $HOME/.local/bin
        curl -L https://github.com/dahlia/seonbi/releases/download/0.3.1/seonbi-0.3.1.linux-x86_64.tar.bz2 \
        | tar xvfj -
        popd
        export PATH="$HOME/.local/bin:$PATH"
        make

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
