name: Publish
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nikeee/setup-pandoc@v1
    - uses: dahlia/seonbi/setup@main
      with:
        submark-version: 0.3.*
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y fonts-noto-cjk texlive-xetex
    - run: make
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
